option1dict = {
    'Boston Celtics': ("Basketball", "Northeast"),
    'Brooklyn Nets': ("Basketball", "Northeast"),
    'New York Knicks': ("Basketball", "Northeast"),
    'Philadelphia 76ers': ("Basketball", "Northeast"),
    'Toronto Raptors': ("Basketball", "Northeast"),
    'Chicago Bulls': ("Basketball", "Midwest"),
    'Cleveland Cavaliers': ("Basketball", "Midwest"),
    'Detroit Pistons': ("Basketball", "Midwest"),
    'Indiana Pacers': ("Basketball", "Midwest"),
    'Milwaukee Bucks': ("Basketball", "Midwest"),
    'Atlanta Hawks': ("Basketball", "Southeast"),
    'Charlotte Hornets': ("Basketball", "Southeast"),
    'Miami Heat': ("Basketball", "Southeast"),
    'Orlando Magic': ("Basketball", "Southeast"),
    'Washington Wizards': ("Basketball", "Southeast"),
    'Denver Nuggets': ("Basketball", "West"),
    'Minnesota Timberwolves': ("Basketball", "West"),
    'Oklahoma City Thunder': ("Basketball", "West"),
    'Portland Trail Blazers': ("Basketball", "West"),
    'Utah Jazz': ("Basketball", "West"),
    'Golden State Warriors': ("Basketball", "West"),
    'LA Clippers': ("Basketball", "West"),
    'Los Angeles Lakers': ("Basketball", "West"),
    'Phoenix Suns': ("Basketball", "West"),
    'Sacramento Kings': ("Basketball", "West"),
    'Dallas Mavericks': ("Basketball", "Southwest"),
    'Houston Rockets': ("Basketball", "Southwest"),
    'Memphis Grizzlies': ("Basketball", "Southwest"),
    'New Orleans Pelicans': ("Basketball", "Southwest"),
    'Buffalo Bills' : ("Football", "Northeast"),
    'Miami Dolphins' :  ("Football", "Northeast"),
    'New England Patriots' : ("Football", "Northeast"),
    'New York Jets' : ("Football", "Northeast"),
    'Baltimore Ravens' : ("Football", "Northeast"),
    'Cincinnati Bengals' : ("Football", "Northeast"),
    'Cleveland Browns': ("Football", "Northeast"),
    'Pittsburgh Steelers': ("Football", "Northeast"),
    'Houston Texans': ("Football", "Southeast"),
    'Indianapolis Colts': ("Football", "Southeast"),
    'Jacksonville Jaguars': ("Football", "Southeast"),
    'Tennessee Titans': ("Football", "Southeast"),
    'Denver Broncos': ("Football", "Midwest"),
    'Kansas City Chiefs': ("Football", "Midwest"),
    'Las Vegas Raiders': ("Football", "Midwest"),
    'Los Angeles Chargers': ("Football", "Midwest"),
    'Dallas Cowboys': ("Football", "Southeast"),
    'New York Giants': ("Football", "Southeast"),
    'Philadelphia Eagles': ("Football", "Southeast"),
    'Washington Commanders': ("Football", "Southeast"),
    'Chicago Bears': ("Football", "Midwest"),
    'Detroit Lions': ("Football", "Midwest"),
    'Green Bay Packers': ("Football", "Midwest"),
    'Minnesota Vikings': ("Football", "Midwest"),
    'Atlanta Falcons': ("Football", "Southwest"),
    'Carolina Panthers': ("Football", "Southwest"),
    'New Orleans Saints': ("Football", "Southwest"),
    'Tampa Bay Buccaneers': ("Football", "Southwest"),
    'Arizona Cardinals': ("Football", "West"),
    'Los Angeles Rams': ("Football", "West"),
    'San Francisco 49ers': ("Football", "West"),
    'Seattle Seahawks': ("Football", "West"),
    'Chicago White Sox': ("Baseball", "Midwest"),
    'Cleveland Guardians': ("Baseball", "Midwest"),
    'Detroit Tigers': ("Baseball", "Midwest"),
    'Kansas City Royals': ("Baseball", "Midwest"),
    'Minnesota Twins': ("Baseball", "Midwest"),
    'Baltimore Orioles': ("Baseball", "Northeast"),
    'Boston Red Sox': ("Baseball", "Northeast"),
    'New York Yankees': ("Baseball", "Northeast"),
    'Tampa Bay Rays': ("Baseball", "Northeast"),
    'Toronto Blue Jays': ("Baseball", "Northeast"),
    'Houston Astros': ("Baseball", "Southwest"),
    'Los Angeles Angels': ("Baseball", "Southwest"),
    'Oakland Athletics': ("Baseball", "Southwest"),
    'Seattle Mariners': ("Baseball", "Southwest"),
    'Texas Rangers': ("Baseball", "Southwest"),
    'Chicago Cubs': ("Baseball", "Southeast"),
    'Cincinnati Reds': ("Baseball", "Southeast"),
    'Milwaukee Brewers': ("Baseball", "Southeast"),
    'Pittsburgh Pirates': ("Baseball", "Southeast"),
    'St. Louis Cardinals': ("Baseball", "Southeast"),
    'Atlanta Braves': ("Baseball", "Northeast"),
    'Miami Marlins': ("Baseball", "Northeast"),
    'New York Mets': ("Baseball", "Northeast"),
    'Philadelphia Phillies': ("Baseball", "Northeast"),
    'Washington Nationals': ("Baseball", "Northeast"),
    'Arizona Diamondbacks': ("Baseball", "West"),
    'Colorado Rockies': ("Baseball", "West"),
    'Los Angeles Dodgers': ("Baseball", "West"),
    'San Diego Padres': ("Baseball", "West"),
    'San Francisco Giants': ("Baseball", "West"),
    'Atlanta United': ("Soccer", "Southeast"),
    'Austin FC': ("Soccer", "Southeast"),
    'Charlotte FC': ("Soccer", "Southeast"),
    'Chicago Fire FC': ("Soccer", "Midwest"),
    'FC Cincinnati': ("Soccer", "Northeast"),
    'Colorado Rapids': ("Soccer", "Northeast"),
    'Columbus Crew': ("Soccer", "Northeast"),
    'D.C. United': ("Soccer", "Northeast"),
    'FC Dallas': ("Soccer", "Southwest"),
    'Houston Dynamo FC': ("Soccer", "Southwest"),
    'Sporting Kansas City': ("Soccer", "Midwest"),
    'LA Galaxy': ("Soccer", "West"),
    'Los Angeles Football Club': ("Soccer", "West"),
    'Inter Miami CF': ("Soccer", "Southeast"),
    'Minnesota United': ("Soccer", "Midwest"),
    'CF Montréal': ("Soccer", "Northeast"),
    'Nashville SC': ("Soccer", "Southwest"),
    'New England Revolution': ("Soccer", "Northeast"),
    'New York Red Bulls': ("Soccer", "Northeast"),
    'New York City FC': ("Soccer", "Northeast"),
    'Orlando City': ("Soccer", "Northeast"),
    'Philadelphia Union': ("Soccer", "Northeast"),
    'Portland Timbers': ("Soccer", "West"),
    'Real Salt Lake': ("Soccer", "Midwest"),
    'San Jose Earthquakes': ("Soccer", "West"),
    'Seattle Sounders FC': ("Soccer", "West"),
    'Toronto FC': ("Soccer", "Northeast"),
    'Vancouver Whitecaps FC': ("Soccer", "Northeast")
}

option2dict = {
    'Coco': ("Action", "0-12"),
    'Zootopia': ("Action", "0-12"),
    'Moana': ("Action", "0-12"),
    'Beauty and the Beast': ("Action", "0-12"),
    'Finding Dory': ("Comedy" "0-12"),
    'Cars 3': ("Action", "0-12"),
    'A Wrinkle in Time': ("Action", "0-12"),
    'Incredibles 2': ("Action", "0-12"),
    'Guardians of the Galaxy, Vol. 2': ("Action", "13-18"),
    'Rogue One: A Star Wars Story': ("Action", "13-18"),
    'Doctor Strange': ("Action", "13-18"),
    'The Jungle Book': ("Action", "13-18"),
    'Captain America: Civil War': ("Action", "13-18"),
    'Alice Through the Looking Glass': ("Action", "13-18"),
    'Star Wars: The Force Awakens': ("Action", "13-18"),
    'Pirates of the Caribbean: Dead Men Tell No Tales': ("Action", "13-18"),
    'Thor: Ragnarok': ("Action", "13-18"),
    'Star Wars: The Last Jedi': ("Action", "13-18"),
    'Black Panther': ("Action", "13-18"),
    'Avengers: Infinity War ': ("Action", "13-18"),
    'Ant-Man and The Wasp': ("Action", "13-18"),
    'Captain Marvel': ("Action", "13-18"),
    'Avengers: Endgame': ("Action", "13-18"),
    'Star Wars: The Rise of Skywalker': ("Action", "13-18"),
    'Stargirl': ("Action", "13-18"),
    'Cruella': ("Action", "13-18"),
    'Shang-Chi and the Legend of the Ten Rings': ("Action", "13-18"),
    'Eternals': ("Action", "13-18"),
    'Doctor Strange in the Multiverse of Madness': ("Action", "13-18"),
    'Black Widow': ("Action", "13-18"), 
    'Maleficent: Mistress of Evil': ("Action", "13-18"),
    'Solo: A Star Wars Story': ("Action", "13-18"),
    'Pulp Fiction': ("Action", "19-24"),
    'Reservoir Dogs': ("Action", "19-24"),
    'Inglourious Basterds': ("Action", "19-24"),
    'Django Unchained': ("Action", "19-24"),
    'Jackie Brown': ("Action", "19-24"),
    'Once Upon a Time... In Hollywood': ("Action", "19-24"),
    'Kill Bill: Vol. 1': ("Action", "19-24"),
    'The One and Only Ivan': ("Comedy", "0-12"),
    'Christopher Robin': ("Comedy", "0-12"),
    'Ralph Breaks the Internet': ("Comedy", "0-12"),
    'Jungle Cruise': ("Comedy", "0-12"),
    'Diary of a Wimpy Kid': ("Comedy", "0-12"),
    'Dog': ("Comedy", "19-24"),
    'Ghostbusters: Answer the Call': ("Comedy", "19-24"),
    'The Tomorrow War': ("Comedy", "19-24"),
    'Tyler Perrys a Madea Christmas': ("Comedy", "19-24"),
    'Jumanji: Welcome to the Jungle': ("Comedy", "19-24"),
    '21 Jump Street': ("Comedy", "25+"),
    'The Hangover': ("Comedy", "25+"),
    'The 40-Year-Old Virgin': ("Comedy", "25+"),
    'Superbad': ("Comedy", "25+"),
    'Its Kind of a Funny Story': ("Romance", "0-12"),
    'The Princess and the Goblin': ("Romance", "0-12"),
    'Tangled': ("Romance", "0-12"),
    'Be My Valentine, Charlie Brown': ("Romance", "0-12"),
    'The Parent Trap': ("Romance", "0-12"),
    'High School Musical': ("Romance", "0-12"),
    'The Fault in Our Stars': ("Romance", "13-18"),
    'Titanic': ("Romance", "13-18"),
    'The Proposal': ("Romance", "13-18"),
    '10 Things I Hate About You': ("Romance", "13-18"),
    'The Notebook': ("Romance", "13-18"),
    'How to Lose a Guy in 10 Days': ("Romance", "13-18"),
    'After We Fell': ("Romance", "19-24"),
    'After We Collided': ("Romance", "19-24"),
    'No Strings Attached': ("Romance", "19-24"),
    'The Shape of Water': ("Romance", "19-24"),
    'What Men Want': ("Romance", "19-24"),
    'Showgirls': ("Romance", "25+"),
    'Room in Rome': ("Romance", "25+"),
    'Beauty and the Beast': ("Drama", "0-12"),
    'Cow Bells': ("Drama", "0-12"),
    'Ramona and Beezus': ("Drama", "0-12"),
    'Read it and Weep': ("Drama", "0-12"),
    'The Hunchback of Notre Dame': ("Drama", "0-12"),
    'Babe': ("Drama", "0-12"),
    'Babe: Pig in the City': ("Drama", "0-12"),
    'Kidulthood': ("Drama", "13-18"),
    'Twilight': ("Drama", "13-18"),
    'The Inbetweeners Movie': ("Drama", "13-18"),
    'The Edge Of Seventeen': ("Drama", "13-18"),
    'Jennifer’s Body': ("Drama", "13-18"),
    '12 Years a Slave': ("Drama", "19-24"),
    'A Star Is Born': ("Drama", "19-24"),
    'Animal Kingdom': ("Drama", "19-24"),
    'Boys Don’t Cry': ("Drama", "19-24"),
    'Dunkirk': ("Drama", "19-24"),
    'Fences': ("Drama", "19-24"),
    'Good Will Hunting': ("Drama", "19-24"),
    'Hidden Figures': ("Drama", "25+"),
    'In the Heat of the Night': ("Drama", "25+"),
    'Jaws': ("Drama", "25+"),
    'Selma': ("Drama", "25+"),
    'The Boy Who Harnessed the Wind': ("Drama", "25+"),
    'Lady Bird': ("Comedy", "13-18"),
    'Let It Snow': ("Comedy", "13-18"),
    'The Package': ("Comedy", "13-18"),
    'The Perfect Date': ("Comedy", "13-18"),
    'The Edge Of Seventeen': ("Comedy", "13-18")
}

option3dict = {
    'Astro’s Playroom': ("Playstation", "Puzzle"),
    'Deathloop': ("Playstation", "Shooter"),
    'Demon’s Souls': ("Playstation", "RPG"),
    'Destruction AllStars': ("Playstation", "Shooter"),
    'Final Fantasy VII Remake Intergrade': ("Playstation", "RPG"),
    'Ghostwire: Tokyo': ("Playstation", "RPG"),
    'Horizon Forbidden West': ("Playstation", "RPG"),
    'Ratchet & Clank: Rift Apart': ("Playstation", "Puzzle"),
    'Returnal': ("Playstation", "RPG"),
    'Spider-Man: Miles Morales': ("Playstation", "RPG"),
    'The Sims': ("Playstation", "Simulator"),
    'Immortality': ("Xbox", "RPG"),
    'Rare Replay': ("Xbox", "RPG"),
    'Microsoft Flight Simulator': ("Xbox", "Simulator"),
    'Sable': ("Xbox", "RPG"),
    'Quantum Break': ("Xbox", "RPG"),
    'Halo: The Master Chief Collection': ("Xbox", "Shooter"),
    'Sunset Overdrive': ("Xbox", "Shooter"),
    'Forza Motorsport 7': ("Xbox", "Simulator"),
    'Ori and the Will of the Wisps': ("Xbox", "Puzzle"),
    'BeamNG.drive': ("PC", "Simulator"),
    'Factorio': ("PC", "Puzzle"),
    'World of Warcraft': ("PC", "RPG"),
    'Age of Empires II: Definitive Edition': ("PC", "Simulator"),
    'Endless Legend': ("PC", "RPG"),
    'Valorant': ("PC", "Shooter"),
    'Team Fortress 2': ("PC", "Shooter"),
    'Super Mario Odyssey': ("Nintendo Switch", "RPG"),
    'Splatoon 3': ("Nintendo Switch", "Shooter"),
    'Animal Crossing: New Horizons': ("Nintendo Switch", "RPG"),
    'Tetris 99': ("Nintendo Switch", "Puzzle"),
    'Fast RMX': ("Nintendo Switch", "Simulator"),
    'Marvel Ultimate Alliance 3: The Black Order': ("Nintendo Switch", "RPG"),
    'ARMS': ("Nintendo Switch", "RPG")


}

option4dict = {
    'Take Five by Dave Brubeck': ("Jazz", "0-12"),
    'So What by Miles Davis': ("Jazz", "13-18"),
    'Take The A Train by Duke Ellington': ("Jazz", "19-24"),
    'Round Midnight by Thelonious Monk': ("Jazz", "25+"),
    'My Favorite Things by John Coltrane': ("Jazz", "0-12"),
    'A Love Supreme by John Coltrane': ("Jazz", "13-18"),
    'All Blues by Miles Davis': ("Jazz", "19-24"),
    'Birdland by Weather Report': ("Jazz", "25+"),
    'The Girl From Ipanema by Stan Getz and Astrud Gilberto': ("Jazz", "0-12"),
    'Sing, Sing, Sing by Benny Goodman': ("Jazz", "13-18"),
    'Strange Fruit by Billie Holiday': ("Jazz", "19-24"),
    'A Night in Tunisia	by Dizzy Gillespie': ("Jazz", "25+"),
    'Giant Steps	by John Coltrane': ("Jazz", "0-12"),
    'Blue Rondo a la Turk by Dave Brubeck': ("Jazz", "13-18"),
    'Goodbye Pork Pie Hat by Charles Mingus': ("Jazz", "19-24"),
    'Sunflower by Post Malone and Swae Lee': ("Rap", "0-12"),
    'Fallen by Jaden Smith': ("Rap", "0-12"),
    'Baby Shark Remix by Lil Donald': ("Rap", "0-12"),
    'Despicable Me by Pharrell Williams': ("Rap", "0-12"),
    'I Like To Move It by Will.I.Am': ("Rap", "0-12"),
    'Shotta Flow by NLE Choppa': ("Rap", "13-18"),
    'F.N by Lil Tjay': ("Rap", "13-18"),
    'Money In The Grave by Drake and Rick Ross': ("Rap", "13-18"),
    'Old Town Road by Lil Nas X': ("Rap", "13-18"),
    'Homicide by Logic': ("Rap", "13-18"),
    'Magnolia by Playboi Carti': ("Rap", "19-24"),
    'D Rose by Lil Pump': ("Rap", "19-24"),
    'THE RACE by TAY-K ': ("Rap", "19-24"),
    'Rich Sex by Future': ("Rap", "25+"),
    'It’s Goin’ Down by Celly Cel ': ("Rap", "25+"),
    'Pussycat by Missy Elliott ': ("Rap", "25+"),
    'Lollipop by Lil Wayne and Static Major ': ("Rap", "25+"),
    'Half Of Me by Thomas Rhett feat. Riley Green': ("Country", "0-12"),
    '5 Foot 9 by Tyler Hubbard': ("Country", "0-12"),
    'Dont Come Lookin by Jackson Dean': ("Country", "0-12"),
    'Fall In Love by Bailey Zimmerman': ("Country", "0-12"),
    'Down home by Jimmie Allen': ("Country", "0-12"),
    'Country On by Luke Bryan': ("Country", "13-18"),
    'Son Of A Sinner by Jelly Roll': ("Country", "13-18"),
    'Pick Me Up by Gabby Barrett': ("Country", "13-18"),
    'Whiskey On You by Nate Smith': ("Country", "19-24"),
    'Thank God by Kane Brown and Katelyn Brown': ("Country", "19-24"),
    'Heart Like A Truck by Lainey Wilson': ("Country", "19-24"),
    'Going, Going, Gone by Luke Combs': ("Country", "25+"),
    'Gold by Dierks Bentley': ("Country", "25+"),
    'Joy Of My Life by Chris Stapleton': ("Country", "25+"),
    'Brown Eyes Baby by Keith Urban': ("Country", "25+"),
    'Purple Haze by Jimi Hendrix': ("Rock", "0-12"),
    'Whole Lotta Love by Led Zeppelin': ("Rock", "0-12"),
    'Sympathy for the Devil by The Rolling Stones': ("Rock", "0-12"),
    'Under Pressure by Queen & David Bowie': ("Rock", "0-12"),
    'Comfortably Numb by Pink Floyd': ("Rock", "13-18"),
    'I Love Rock n Roll by Joan Jett & the Blackhearts': ("Rock", "13-18"),
    'Funk #49 by the James Gang': ("Rock", "13-18"),
    'The Boys Are Back in Town by Thin Lizzy': ("Rock", "13-18"),
    'Iron Man by Black Sabbath': ("Rock", "19-24"),
    'Barracuda by Heart': ("Rock", "19-24"),
    'Smoke on the Water by Deep Purple': ("Rock", "19-24"),
    'Frankenstein by the Edgar Winter Group': ("Rock", "19-24"),
    'La Grange by ZZ Top': ("Rock", "25+"),
    'American Girl by Tom Petty & the Heartbreakers': ("Rock", "25+"),
    'You Really Got Me by The Kinks': ("Rock", "25+"),
    'Charity Ball by Fanny': ("Rock", "25+")


}
